

# @baseUrl = https://specifics.fyi
@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsInBob25lTnVtYmVyIjoiKzkxODAwNzIwNDEzMyIsImlhdCI6MTczOTg5MTY5MSwiZXhwIjoxNzUyODUxNjkxfQ.ki3xzCYIceGt2X3iFrTEgSqDsf2qN5e84V8boITQggs
@sessionId = 72b32a85-35e1-460e-85e2-bac96f0a70ff
@entryId = 69e5e597-9e36-4acf-aa07-4d90148d17bc

### Get all sessions for user
GET {{baseUrl}}/sessions
Authorization: Bearer {{token}}

### Start a new session
GET {{baseUrl}}/sessions/start
Authorization: Bearer {{token}}

### End a session
GET {{baseUrl}}/sessions/{{sessionId}}/end
Authorization: Bearer {{token}}

### Get next question for a session
GET {{baseUrl}}/sessions/{{sessionId}}/next-question
Authorization: Bearer {{token}}

### Add answer to a question in a session
POST  {{baseUrl}}/sessions/{{sessionId}}/add-answer/{{entryId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "answer": "I dont know keep quite"
}

### Get all entries for a session
GET {{baseUrl}}/sessions/{{sessionId}}/entries
Authorization: Bearer {{token}}